# Generated by Django 3.2 on 2022-11-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('arrival_point', models.CharField(max_length=150)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transporter_commission', models.DecimalField(decimal_places=2, max_digits=6)),
                ('africarelais_commission', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relayer_commission', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DeparturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('tracking_code', models.CharField(max_length=8, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PG', 'En préparation'), ('AD', 'Arrivé au point relais'), ('IP', 'En cours de livraison'), ('RD', 'Reçu par le client')], default='PG', max_length=155)),
                ('mode', models.CharField(choices=[('HM', 'Domicile'), ('PR', 'Point relais')], default='HM', max_length=155)),
                ('pack', models.CharField(choices=[('ST', 'Standards'), ('EX', 'Express'), ('EC', 'Economique')], default='ST', max_length=155)),
                ('weight', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='packages/%Y/%m%d')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tracking_number', models.CharField(max_length=8, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.contact')),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_points', to='delivery.deliverypoint')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='departure_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.departurepoint'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=155)),
                ('client_phone', models.CharField(max_length=155)),
                ('paid', models.BooleanField(default=False)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.package')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='deliverypoint',
            unique_together={('departure_point', 'arrival_point')},
        ),
    ]
