# Generated by Django 3.2 on 2022-11-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AfricaRelais', max_length=150)),
                ('description', models.TextField(default='AfricaRelais')),
                ('link_to', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user_name', models.CharField(max_length=60)),
                ('platfom', models.CharField(choices=[('Youtube', 'Youtube'), ('Linkedin', 'Linkedin'), ('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], default='Linkedin', max_length=20)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='testimonial/user/')),
                ('user_title', models.CharField(max_length=60, null=True)),
                ('capture', models.ImageField(blank=True, null=True, upload_to='testimonial/capture/')),
            ],
        ),
        migrations.CreateModel(
            name='RelayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Dakar', max_length=155)),
                ('address', models.CharField(default='Dakar', max_length=155)),
                ('pluscode', models.CharField(default='Dakar', max_length=155)),
                ('phone', models.CharField(max_length=155, null=True)),
                ('email', models.CharField(max_length=155, null=True)),
                ('friday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('saturday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('sunday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('monday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('tuesday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('wednesday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('thursday', models.CharField(default='8a.m  6p.m.', max_length=155)),
                ('latitude', models.DecimalField(decimal_places=7, default=14.71331, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=7, default=-17.45472, max_digits=30)),
                ('name', models.CharField(default='Hlm', max_length=155)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=155)),
                ('client_email', models.CharField(max_length=155, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='page.relaypoint')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_from', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('weekday_to', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)])),
                ('to_hour', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)])),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.relaypoint')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=160, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientRealyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relay_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.relaypoint')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
